do not deploy empty package set with pacman
AppImageCrafters/appimage-builder pull request #266
Opened 2022-10-05 08:04 UTC by iTrooz

appimage-builder currently crashes with this config because it tries to do something like `pacman -S` (with no packages appended):
```yml
pacman:
  include: []
```

I simply copied this block from the apt deploy script to fix it : https://github.com/AppImageCrafters/appimage-builder/blob/bd82930fccbe63a0d412288d9b645adb951f65ee/appimagebuilder/modules/deploy/apt/deploy.py#L35

2022-10-05 15:49 UTC, azubieta requested changes
Seems good, just remove the debug comment.

2022-10-05 15:49 UTC, azubieta commented on appimagebuilder/modules/deploy/pacman/deploy.py
> +        print("AAAAAAAAAAAAAAAAAAAAA")
Please don't include debug information

2022-10-05 16:14 UTC, iTrooz commented
Oops, done !

2022-10-06 14:39 UTC, azubieta approved these changes

2022-10-06 14:39 UTC, merged

2022-10-06 14:39 UTC, azubieta commented
Thanks for helping!